apiRules:
- exclude:
      uidRegex: ^System\.Object
      type: Type
- exclude:
      uidRegex: ^System\.Windows
      type: Type
- exclude:
      uidRegex: ^System\.ComponentModel
      type: Type
- exclude:
      uidRegex: ^Stylet
      type: Type
- exclude:
      uidRegex: ^Artemis\.Core\.CorePropertyChanged
      type: Type
- exclude:
      uidRegex: ^Artemis\.Core\.Properties
      type: Type
- exclude:
      uidRegex: ^Artemis\.Core\.Services\.IArtemisService
      type: Type
- exclude:
      uidRegex: ^Artemis\.UI\.Shared\.Properties
      type: Type
- exclude:
      uidRegex: ^Artemis\.Core\.TypeExtensions\.IsNumber
      type: Method